export const MOCK_LISTS = [
  {
    id: "1",
    title: "Family-Friendly European Cities with Kids Under 5",
    description: "Perfect destinations for young families with playgrounds, museums, and child-friendly restaurants",
    author: {
      id: "user1",
      name: "Sarah Parker",
      avatar: "/avatars/sarah.jpg",
      location: "London, UK",
      bio: "Family travel expert, mom of two, and former kindergarten teacher. Sharing kid-friendly destinations across Europe.",
    },
    places: [
      {
        id: "copenhagen-denmark",
        name: "Copenhagen",
        country: "Denmark",
        imageUrl: "copenhagen-denmark-1",
        description:
          "A family paradise with interactive museums, safe cycling paths, and the magical Tivoli Gardens. The city's compact size and excellent public transportation make it perfect for families with young children.",
        highlight: "Tivoli Gardens, Denmark's National Aquarium, and Copenhagen Zoo",
        rating: 4.8,
        reviews: 1456,
        coordinates: [55.6761, 12.5683],
        tags: ["family-friendly", "museums", "parks", "safe", "cycling"],
        bestTime: "May-September",
        suggestedStay: "4-5 days",
      },
      {
        id: "amsterdam-netherlands",
        name: "Amsterdam",
        country: "Netherlands",
        imageUrl: "amsterdam-netherlands-1",
        description:
          "Despite its reputation, Amsterdam is incredibly family-friendly with numerous parks, interactive museums, and pancake houses. The NEMO Science Museum and Vondelpark are must-visits for families.",
        highlight: "NEMO Science Museum, Vondelpark, and Canal Boat Tours",
        rating: 4.7,
        reviews: 2134,
        coordinates: [52.3676, 4.9041],
        tags: ["family-friendly", "museums", "parks", "boat-tours"],
        bestTime: "April-October",
        suggestedStay: "3-4 days",
      },
      {
        id: "munich-germany",
        name: "Munich",
        country: "Germany",
        imageUrl: "munich-germany-1",
        description:
          "Home to the incredible Deutsches Museum, English Garden, and numerous family-friendly beer gardens with playgrounds. The city offers a perfect blend of culture and outdoor activities for families.",
        highlight: "Deutsches Museum, English Garden, and Hellabrunn Zoo",
        rating: 4.9,
        reviews: 1897,
        coordinates: [48.1351, 11.582],
        tags: ["family-friendly", "museums", "parks", "zoo"],
        bestTime: "May-September",
        suggestedStay: "4-5 days",
      },
    ],
    stats: {
      views: 45678,
      likes: 1242,
      saves: 456,
      shares: 89,
    },
    metadata: {
      createdAt: "2024-03-15",
      updatedAt: "2024-03-15",
      isVerified: true,
      category: "Family Travel",
    },
    tags: ["family", "kids", "europe", "playgrounds", "museums", "child-friendly"],
    relatedLists: [
      {
        id: "family-friendly-beaches",
        title: "Best Beach Cities for Young Families",
        places: 6,
        author: "Emma Wilson",
        imageUrl: "nice-france-1",
      },
      {
        id: "museum-cities",
        title: "Europe's Most Interactive Museums for Kids",
        places: 8,
        author: "Mark Stevens",
        imageUrl: "london-uk-1",
      },
    ],
    totalPlaces: 3,
  },
  {
    id: "2",
    title: "Portland's Hidden Gem Restaurants 2024",
    description: "Local food critic's guide to the most underrated eateries in PDX, from hole-in-the-wall spots to innovative food carts",
    author: {
      id: "user2",
      name: "Mike Chen",
      avatar: "/avatars/mike.jpg",
      location: "Portland, OR",
      bio: "Food critic for The Oregonian, cookbook author, and Portland native sharing the city's best kept culinary secrets.",
    },
    places: [
      {
        id: "portland-downtown",
        name: "Portland Downtown",
        country: "United States",
        imageUrl: "portland-downtown-1",
        description:
          "Portland's downtown district is a treasure trove of hidden culinary gems, from basement ramen shops to rooftop farm-to-table experiences. The food cart pods offer some of the most innovative cuisine in the city.",
        highlight: "Food Cart Pods, Underground Speakeasies, and Pop-up Restaurants",
        rating: 4.9,
        reviews: 3456,
        coordinates: [45.5155, -122.6789],
        tags: ["food-carts", "fine-dining", "fusion", "farm-to-table"],
        bestTime: "Year-round",
        suggestedStay: "3-4 days",
      },
    ],
    stats: {
      views: 28945,
      likes: 892,
      saves: 567,
      shares: 234,
    },
    metadata: {
      createdAt: "2024-03-10",
      updatedAt: "2024-03-14",
      isVerified: true,
      category: "Food & Dining",
    },
    tags: ["food", "local", "portland", "restaurants", "food-carts", "hidden-gems"],
    relatedLists: [
      {
        id: "pdx-breakfast",
        title: "Portland's Best Breakfast Spots",
        places: 12,
        author: "Sarah Lee",
        imageUrl: "portland-breakfast-1",
      },
      {
        id: "pdx-food-carts",
        title: "Ultimate PDX Food Cart Guide",
        places: 20,
        author: "Mike Chen",
        imageUrl: "portland-carts-1",
      },
    ],
    totalPlaces: 15,
  },
];
