name: Deploy migrations to CitiesRank PPE DB
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        SSH_PRIVATE_KEY: ${{secrets.AZ_CITIESRANK_VM_KEY}}
        SSH_KEY_PATH: ~/.ssh/
        SSH_KEY_NAME: private.key
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ${{env.SSH_KEY_PATH}}/${{env.SSH_KEY_NAME}}
          sudo chmod 600 ${{env.SSH_KEY_PATH}}/${{env.SSH_KEY_NAME}}
          ssh-keyscan -H citiesrank-ppe.westus2.cloudapp.azure.com > ${{env.SSH_KEY_PATH}}/known_hosts
        shell: bash
        
      - name: Copy migrations to VM
        run: |
          ssh -i ${{env.SSH_KEY_PATH}}/${{env.SSH_KEY_NAME}}}} citiesrank-ppe-admin@citiesrank-ppe.westus2.cloudapp.azure.com 'mkdir -p ~/pb/pb_migrations'
          scp -i ${{env.SSH_KEY_PATH}}/${{env.SSH_KEY_NAME}}}} -r pocketbase/pb_migrations/* citiesrank-ppe-admin@citiesrank-ppe.westus2.cloudapp.azure.com:~/pb/pb_migrations/
          # Restart the pocketbase service to apply the migrations
          ssh -i ${{env.SSH_KEY_PATH}}/${{env.SSH_KEY_NAME}}}} citiesrank-ppe-admin@citiesrank-ppe.westus2.cloudapp.azure.com 'sudo systemctl restart pocketbase'